language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: "Dq/epvu++7flgRS7J6vrmP3RYlY9UMuSvlRG1ChiIiCn5lDop7nmf/6Wgierg02cOJXGmSFQ3/wiAt1H9W4ERxvn9ausfToMcM/VKcpY5+hZHB6yIKRwvdfLw0MNv4UfvGBysj0cN+Y55PAJSJbG6SB+zF/iHMMfFltVby/aaLQ="
  file_glob: true
  file: "build/libs/FixChat-*-all.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
sudo: false
